#### Data cleaning : Employee Dataset

In [115]:
# import libraries 
import numpy as np 
import pandas as pd

In [116]:
# load dataset
df = pd.read_csv('Messy_Employee_dataset.csv')
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [117]:
# understand the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   str
 1   First_Name         1020 non-null   str
 2   Last_Name          1020 non-null   str
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   str
 5   Status             1020 non-null   str
 6   Join_Date          1020 non-null   str
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   str
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   str
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(8)
memory usage: 165.7 KB

In [118]:
df.shape

(1020, 12)

In [119]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region',
       'Status', 'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score',
       'Remote_Work'],
      dtype='str')

##### Data cleaning

In [120]:
# check missing values

df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [121]:
df['Age'] = df['Age'].fillna(df['Age'].mean(),inplace = True) 

# check age dtype to int 
df['Age'] = df['Age'].astype(int)

df['Age'].dtype

C:\Users\shali\AppData\Local\Temp\ipykernel_16028\949568638.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'] = df['Age'].fillna(df['Age'].mean(),inplace = True)

dtype('int64')

In [122]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean(),inplace=True)

C:\Users\shali\AppData\Local\Temp\ipykernel_16028\3687860956.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Salary'] = df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [123]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,32,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,32,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [124]:
df['Salary'] = df['Salary'].astype(int)
df['Salary'].dtype

dtype('int64')

In [125]:
# Remove duplicates
df.duplicated().sum() # no duplicates found
# df.drop_duplicates(inplace=True) if duplicate use this

np.int64(0)

In [128]:
# standrized text
df['Employee_ID'] = df['Employee_ID'].str.replace("EMP","",regex=False)
df['Employee_ID'] = df['Employee_ID'].astype('int')

In [ ]:
# Combine first_name and last_name in name
df['Name'] = df['First_Name'] + " " + df['Last_Name']

In [130]:
# move name column to first position
df.insert(1,"Name", df.pop("Name"))

In [131]:
# drop first name and last name columns
df.drop(columns=['First_Name','Last_Name'],inplace=True)

In [132]:
# split Department_Region to Depart and Region 
df[["Department", "Region"]] = df["Department_Region"].str.split("-", expand=True)

In [133]:
df.drop(columns=['Department_Region'],inplace=True)

In [136]:
# Fix joining date 
df['Join_Date'] = pd.to_datetime(df['Join_Date'], format='mixed')

In [ ]:
df['Phone'] = df['Phone'].astype('str')
df['Phone'] = df['Phone'].str.replace("-"," ",regex=False)
df['Phone'] = df['Phone'].astype('int')

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x=df['Salary'])

# No outliers there : no need to remove outliers in many case so skip it

In [157]:
# Save this cleaned data for EDA
df.to_csv('Cleaned_Employee_dataset.csv',index=False)